use std::path::{Path, PathBuf};

macro_rules! includes {
    ($($h:expr),* $(,)?) => {
        vec![$($h.into()),*]
    };
}

// List include directives needed by each crate header.
fn configure(name: &str, mut config: cbindgen::Config) -> cbindgen::Config {
    // Rename structs from `ExampleT` to `mongoac_example_t`.
    for (from, to) in [
        ("ClientOptionsT", "mongoac_client_options_t"),
        ("ClientSessionT", "mongoac_client_session_t"),
        ("ClientT", "mongoac_client_t"),
        ("CollectionT", "mongoac_collection_t"),
        ("CursorT", "mongoac_cursor_t"),
        ("DatabaseT", "mongoac_database_t"),
        ("ErrorT", "mongoac_error_t"),
        ("FutureT", "mongoac_future_t"),
        ("RuntimeT", "mongoac_runtime_t"),
    ] {
        config
            .export
            .rename
            .insert(from.to_string(), to.to_string());
    }

    config.sys_includes = match name {
        "sanity_check" => includes!["mongoac/export.h", "stdint.h"],
        "client" => includes![
            "mongoac/export.h",
            "mongoac/client_options.h",
            "mongoac/client_session.h",
            "mongoac/cursor.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "mongoac/runtime.h",
            "bson/bson_t.h",
            "stdbool.h",
            "stdint.h",
        ],
        "client_session" => includes!["mongoac/export.h", "mongoac/future.h"],
        "error" => includes!["mongoac/export.h", "stdbool.h", "stdint.h"],
        "future" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "bson/bson_t.h",
            "stdint.h",
        ],
        "client_options" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "bson/bson_t.h",
            "stdbool.h",
        ],
        "runtime" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "stdint.h"
        ],
        "database" => includes![
            "mongoac/export.h",
            "mongoac/client.h",
            "mongoac/client_session.h",
            "mongoac/cursor.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "bson/bson_t.h",
            "stdbool.h",
            "stdint.h",
        ],
        "collection" => includes![
            "mongoac/export.h",
            "mongoac/database.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "bson/bson_t.h",
            "stdbool.h",
            "stdint.h",
        ],
        "cursor" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "bson/bson_t.h",
            "stdbool.h",
            "stdint.h",
        ],
        _ => vec![],
    };
    config
}

fn generate_crate_header(crate_path: &Path, src_dir: &Path, include_dir: &Path) {
    let file_stem = crate_path
        .file_stem()
        .and_then(|s| s.to_str())
        .expect("invalid UTF-8");

    // These crates must not generate a header.
    // Keep synchronized with `skip_cargo_headers` in src/libmongoac/CMakeLists.txt.
    const SKIP_CARGO_HEADERS: &[&str] = &["lib", "mod", "version"];
    if SKIP_CARGO_HEADERS.contains(&file_stem) {
        return;
    }

    // `src/libmongoac/src/path/to/crate.rs` -> `path/to/crate`
    let rel_path = crate_path
        .strip_prefix(src_dir)
        .expect("file not under src root");
    let rel_stem = rel_path.with_extension("");
    let rel_str = rel_stem.to_str().expect("invalid UTF-8");

    // `path/to/crate` -> `MONGOAC_PATH_TO_CRATE_H`
    let include_guard = format!(
        "MONGOAC_{}_H",
        rel_str
            .replace(std::path::MAIN_SEPARATOR, "_")
            .to_uppercase()
    );

    // `path/to/crate` -> `<include_dir>/path/to/crate.h`
    let header_path = include_dir.join(&rel_stem).with_extension("h");
    if let Some(parent) = header_path.parent() {
        std::fs::create_dir_all(parent)
            .unwrap_or_else(|_| panic!("failed to create include directory: {}", parent.display()));
    }

    // Default cbindgen configuration for all crates.
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        style: cbindgen::Style::Type,
        autogen_warning: Some(
            "// Generated by src/libmongoac/cmake/generate-crate-headers/main.rs".to_owned(),
        ),
        include_version: true,
        cpp_compat: true,
        braces: cbindgen::Braces::NextLine,
        line_length: 120,
        tab_width: 3,
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::C99,
        function: cbindgen::FunctionConfig {
            prefix: Some("MONGOAC_API".to_owned()),
            ..Default::default()
        },
        no_includes: true,
        ..Default::default()
    };

    // Apply per-crate configuration options.
    let config = configure(rel_str, config);

    // Generate the crate header.
    cbindgen::Builder::new()
        .with_config(config)
        .with_include_guard(&include_guard)
        .with_src(crate_path)
        .generate()
        .expect("cbindgen failed")
        .write_to_file(&header_path);
}

// Recursively find all mongoac crates under the source directory which need a header.
fn find_crates(dir: &Path, files: &mut Vec<PathBuf>) {
    for entry in std::fs::read_dir(dir)
        .unwrap_or_else(|_| panic!("failed to read directory: {}", dir.display()))
    {
        let path = entry
            .map(|e| e.path())
            .unwrap_or_else(|_| panic!("failed to read directory entry in: {}", dir.display()));

        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "private") {
                continue; // Private crates do not need headers.
            }

            find_crates(&path, files);
        } else if path.extension().is_some_and(|e| e == "rs") {
            files.push(path);
        }
    }
}

fn main() {
    let src_dir = std::env::var("MONGOAC_SRC_DIR")
        .expect("MONGOAC_SRC_DIR is required (the Rust source root directory)");
    let include_dir = std::env::var("MONGOAC_INCLUDE_DIR")
        .expect("MONGOAC_INCLUDE_DIR is required (the output directory for generated headers)");

    let src_path = Path::new(&src_dir);
    let include_path = Path::new(&include_dir);

    let mut files = Vec::new();
    find_crates(src_path, &mut files);

    // Generate crate headers in parallel.
    let mut handles = Vec::new();
    for path in files {
        let include_dir = include_path.to_path_buf();
        let src_dir = src_path.to_path_buf();
        handles.push(std::thread::spawn(move || {
            generate_crate_header(&path, &src_dir, &include_dir);
        }));
    }
    for handle in handles {
        handle.join().expect("header generation failed");
    }
}
