use std::path::Path;

// Simplify syntax in configure().
macro_rules! includes {
    ($($h:expr),* $(,)?) => {
        vec![$($h.into()),*]
    };
}

// Generate the config.rs crate declaring constants dependent on CMake configuration options.
fn generate_config_crate() {
    use std::fs;
    use std::path::Path;

    let version_current =
        fs::read_to_string("VERSION_CURRENT").expect("src/libmongoac/VERSION_CURRENT is missing");
    let build_type = std::env::var("MONGOAC_CMAKE_BUILD_TYPE").unwrap_or_default();
    let link_type = std::env::var("MONGOAC_LIBRARY_TYPE").unwrap_or_default();

    let full = version_current.trim();

    // Assume valid SemVer string guarantees: regex not required.
    let without_build = full.split('+').next().unwrap_or(full);
    let mut core_and_prerelease = without_build.splitn(2, '-');
    let core = core_and_prerelease.next().unwrap_or(without_build);
    let prerelease = core_and_prerelease.next().unwrap_or("");

    let version: Vec<&str> = core.split('.').collect();

    assert!(
        version.len() == 3,
        "src/libmongoac/VERSION_CURRENT does not contain a valid SemVer string: {}",
        full
    );

    let build_type = match build_type.as_str() {
        "Debug" => "d",
        "Release" | "RelWithDebInfo" | "MinSizeRel" => "r",
        _ => "u",
    };

    let link_type = match link_type.as_str() {
        "shared" => "h",
        "static" => "t",
        _ => "u",
    };

    let file = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is unset")).join("config.rs");

    fs::write(
        &file,
        format!(
            "// Generated by src/libmongoac/build.rs.\n\
             \n\
             pub const MONGOAC_VERSION_MAJOR: i32 = {major};\n\
             pub const MONGOAC_VERSION_MINOR: i32 = {minor};\n\
             pub const MONGOAC_VERSION_PATCH: i32 = {patch};\n\
             pub const MONGOAC_VERSION_PRERELEASE: &str = \"{prerelease}\";\n\
             pub const MONGOAC_VERSION_FULL: &str = \"{full}\";\n\
             pub const MONGOAC_BUILD_PLATFORM: &str = \"{build_type}{link_type}\";\n",
            major = version[0],
            minor = version[1],
            patch = version[2],
            prerelease = prerelease,
            full = full,
            build_type = build_type,
            link_type = link_type,
        ),
    )
    .expect("failed to write config.rs");

    println!("cargo:rerun-if-changed=VERSION_CURRENT");
    println!("cargo:rerun-if-env-changed=MONGOAC_CMAKE_BUILD_TYPE");
    println!("cargo:rerun-if-env-changed=MONGOAC_LIBRARY_TYPE");
}

fn configure(name: &str, mut config: cbindgen::Config) -> cbindgen::Config {
    for (from, to) in [
        ("ClientOptionsT", "mongoac_client_options_t"),
        ("ClientSessionT", "mongoac_client_session_t"),
        ("ClientT", "mongoac_client_t"),
        ("CollectionT", "mongoac_collection_t"),
        ("CursorT", "mongoac_cursor_t"),
        ("DatabaseT", "mongoac_database_t"),
        ("ErrorT", "mongoac_error_t"),
        ("FutureT", "mongoac_future_t"),
        ("RuntimeT", "mongoac_runtime_t"),
    ] {
        config
            .export
            .rename
            .insert(from.to_string(), to.to_string());
    }

    config.sys_includes = match name {
        "sanity_check" => includes!["mongoac/export.h", "stdint.h"],
        "client" => includes![
            "mongoac/export.h",
            "mongoac/client_options.h",
            "mongoac/client_session.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "mongoac/runtime.h",
            "bson/bson_t.h",
            "stdbool.h",
            "stdint.h",
        ],
        "client_session" => includes!["mongoac/export.h", "mongoac/future.h"],
        "error" => includes!["mongoac/export.h", "stdint.h"],
        "future" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "bson/bson_t.h",
            "stdint.h",
        ],
        "client_options" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "bson/bson_t.h",
            "stdbool.h",
        ],
        "runtime" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "stdint.h"
        ],
        "database" => includes![
            "mongoac/export.h",
            "mongoac/client.h",
            "mongoac/client_session.h",
            "mongoac/collection.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "bson/bson_t.h",
            "stdbool.h",
            "stdint.h",
        ],
        "collection" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "bson/bson_t.h",
            "stdbool.h",
            "stdint.h",
        ],
        "cursor" => includes![
            "mongoac/export.h",
            "mongoac/error.h",
            "mongoac/future.h",
            "bson/bson_t.h",
            "stdbool.h",
            "stdint.h",
        ],
        // Per-crate overrides go here.
        _ => vec![],
    };
    config
}

fn generate_crate_header(path: &Path, src_root: &Path, include_dir: &Path) {
    let file_stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .expect("invalid UTF-8");

    const SKIP_CARGO_HEADERS: &[&str] = &["lib", "mod", "version"];
    if SKIP_CARGO_HEADERS.contains(&file_stem) {
        return;
    }

    let rel_path = path
        .strip_prefix(src_root)
        .expect("file not under src root");
    let rel_stem = rel_path.with_extension("");
    let rel_str = rel_stem.to_str().expect("invalid UTF-8");

    println!("cargo:rerun-if-changed={}", path.display());

    let include_guard = format!(
        "MONGOAC_{}_H",
        rel_str
            .replace(std::path::MAIN_SEPARATOR, "_")
            .to_uppercase()
    );
    let output_path = include_dir.join(&rel_stem).with_extension("h");

    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent).expect("failed to create output directory");
    }

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        style: cbindgen::Style::Type,
        autogen_warning: Some("// Generated by src/libmongoac/build.rs.".to_owned()),
        include_version: true,
        cpp_compat: true,
        braces: cbindgen::Braces::NextLine,
        line_length: 120,
        tab_width: 3,
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::C99,
        function: cbindgen::FunctionConfig {
            prefix: Some("MONGOAC_API".to_owned()),
            ..Default::default()
        },
        no_includes: true,
        ..Default::default()
    };

    let config = configure(rel_str, config);

    cbindgen::Builder::new()
        .with_config(config)
        .with_include_guard(&include_guard)
        .with_src(path)
        .generate()
        .expect("cbindgen failed")
        .write_to_file(&output_path);

    // Tell Cargo to rerun build.rs if this generated header is deleted or modified.
    println!("cargo:rerun-if-changed={}", output_path.display());
}

fn collect_files(dir: &Path, files: &mut Vec<std::path::PathBuf>) {
    for entry in std::fs::read_dir(dir).expect("failed to read directory") {
        let entry = entry.expect("failed to read directory entry");
        let path = entry.path();

        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "private") {
                continue;
            }

            collect_files(&path, files);
        } else if path.extension().is_some_and(|e| e == "rs") {
            files.push(path);
        }
    }
}

// Ensure mongoac links with the correct bson library.
fn link_with_bson() {
    fn emit_linkage(env_var: &str, is_shared: bool) {
        let path = std::env::var(env_var).unwrap();
        let path = Path::new(&path);

        assert!(
            path.is_absolute(),
            "{} must be an absolute path, got: {}",
            env_var,
            path.display()
        );

        assert!(
            path.exists(),
            "expected BSON library not found: {}",
            path.display()
        );

        let dir = path
            .parent()
            .unwrap_or_else(|| panic!("{} has no parent directory", env_var));

        println!("cargo:rustc-link-search=native={}", dir.display());

        if is_shared {
            println!("cargo:rustc-link-lib=bson2");
            println!("cargo:rustc-link-arg=-Wl,-rpath,{}", dir.display());
        } else {
            println!("cargo:rustc-link-lib=static=bson2");
        }
    }

    if std::env::var("MONGOAC_BSON_SHARED_LIBRARY_FILENAME").is_ok() {
        emit_linkage("MONGOAC_BSON_SHARED_LIBRARY_FILENAME", true);
    } else if std::env::var("MONGOAC_BSON_STATIC_LIBRARY_FILENAME").is_ok() {
        emit_linkage("MONGOAC_BSON_STATIC_LIBRARY_FILENAME", false);
    }
}

fn main() {
    generate_config_crate();
    link_with_bson();

    // Do not block Rust analyzers which are not aware of the parent CMake configuration.
    let include_dir = match std::env::var("MONGOAC_INCLUDE_DIR") {
        Ok(dir) => Path::new(&dir).join("mongoac"),
        Err(_) => {
            eprintln!("warning: MONGOAC_INCLUDE_DIR unset; skipping C header generation");
            return;
        }
    };

    let src_root = Path::new("src");
    let mut files = Vec::new();
    collect_files(src_root, &mut files);

    // Generate crate headers in parallel.
    let mut handles = Vec::new();
    for path in files {
        let include_dir = include_dir.clone();
        let src_root = src_root.to_path_buf();
        handles.push(std::thread::spawn(move || {
            generate_crate_header(&path, &src_root, &include_dir);
        }));
    }
    for handle in handles {
        handle.join().expect("header generation failed");
    }
}
