// Generate the config.rs crate declaring constants dependent on CMake configuration options.
fn generate_config_crate() {
    use std::fs;
    use std::path::Path;

    let version_current =
        fs::read_to_string("VERSION_CURRENT").expect("src/libmongoac/VERSION_CURRENT is missing");
    let build_type = std::env::var("MONGOAC_CMAKE_BUILD_TYPE").unwrap_or_default();
    let link_type = std::env::var("MONGOAC_LIBRARY_TYPE").unwrap_or_default();

    let full = version_current.trim();

    // Assume valid SemVer string guarantees: regex not required.
    let without_build = full.split('+').next().unwrap_or(full);
    let mut core_and_prerelease = without_build.splitn(2, '-');
    let core = core_and_prerelease.next().unwrap_or(without_build);
    let prerelease = core_and_prerelease.next().unwrap_or("");

    let version: Vec<&str> = core.split('.').collect();

    assert!(
        version.len() == 3,
        "src/libmongoac/VERSION_CURRENT does not contain a valid SemVer string: {}",
        full
    );

    let build_type = match build_type.as_str() {
        "Debug" => "d",
        "Release" | "RelWithDebInfo" | "MinSizeRel" => "r",
        _ => "u",
    };

    let link_type = match link_type.as_str() {
        "shared" => "h",
        "static" => "t",
        _ => "u",
    };

    let file = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is unset")).join("config.rs");

    fs::write(
        &file,
        format!(
            "// Generated by src/libmongoac/build.rs.\n\
             \n\
             pub const MONGOAC_VERSION_MAJOR: i32 = {major};\n\
             pub const MONGOAC_VERSION_MINOR: i32 = {minor};\n\
             pub const MONGOAC_VERSION_PATCH: i32 = {patch};\n\
             pub const MONGOAC_VERSION_PRERELEASE: &str = \"{prerelease}\";\n\
             pub const MONGOAC_VERSION_FULL: &str = \"{full}\";\n\
             pub const MONGOAC_BUILD_PLATFORM: &str = \"{build_type}{link_type}\";\n",
            major = version[0],
            minor = version[1],
            patch = version[2],
            prerelease = prerelease,
            full = full,
            build_type = build_type,
            link_type = link_type,
        ),
    )
    .expect("failed to write config.rs");

    println!("cargo:rerun-if-changed=VERSION_CURRENT");
    println!("cargo:rerun-if-env-changed=MONGOAC_CMAKE_BUILD_TYPE");
    println!("cargo:rerun-if-env-changed=MONGOAC_LIBRARY_TYPE");
}

// Ensure mongoac links with the correct bson library.
fn link_with_bson() {
    use std::path::Path;

    fn emit_linkage(env_var: &str, is_shared: bool) {
        let path = std::env::var(env_var).unwrap();
        let path = Path::new(&path);

        assert!(
            path.is_absolute(),
            "{} must be an absolute path, got: {}",
            env_var,
            path.display()
        );

        assert!(
            path.exists(),
            "expected BSON library not found: {}",
            path.display()
        );

        let dir = path
            .parent()
            .unwrap_or_else(|| panic!("{} has no parent directory", env_var));

        println!("cargo:rustc-link-search=native={}", dir.display());

        if is_shared {
            println!("cargo:rustc-link-lib=bson2");
            println!("cargo:rustc-link-arg=-Wl,-rpath,{}", dir.display());
        } else {
            println!("cargo:rustc-link-lib=static=bson2");
        }
    }

    if std::env::var("MONGOAC_BSON_SHARED_LIBRARY_FILENAME").is_ok() {
        emit_linkage("MONGOAC_BSON_SHARED_LIBRARY_FILENAME", true);
    } else if std::env::var("MONGOAC_BSON_STATIC_LIBRARY_FILENAME").is_ok() {
        emit_linkage("MONGOAC_BSON_STATIC_LIBRARY_FILENAME", false);
    }
}

fn main() {
    generate_config_crate();
    link_with_bson();
}
