// Generated by src/libmongoac/build.rs.
include!(concat!(env!("OUT_DIR"), "/config.rs"));

use crate::string::StringViewT;

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_major() -> i32 {
    MONGOAC_VERSION_MAJOR
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_minor() -> i32 {
    MONGOAC_VERSION_MINOR
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_patch() -> i32 {
    MONGOAC_VERSION_PATCH
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version() -> StringViewT {
    MONGOAC_VERSION_FULL.into()
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_prerelease() -> StringViewT {
    MONGOAC_VERSION_PRERELEASE.into()
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_check(
    required_major: i32,
    required_minor: i32,
    required_patch: i32,
) -> bool {
    let major = mongoac_version_major();
    let minor = mongoac_version_minor();
    let patch = mongoac_version_patch();

    major > required_major
        || (major == required_major && minor > required_minor)
        || (major == required_major && minor == required_minor && patch >= required_patch)
}
