// Generated by src/libmongoac/build.rs.
include!(concat!(env!("OUT_DIR"), "/config.rs"));

use std::ffi::{CString, c_char};
use std::sync::OnceLock;

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_major() -> i32 {
    MONGOAC_VERSION_MAJOR
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_minor() -> i32 {
    MONGOAC_VERSION_MINOR
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_patch() -> i32 {
    MONGOAC_VERSION_PATCH
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version() -> *const c_char {
    static CS: OnceLock<CString> = OnceLock::new();
    // SAFETY: MONGOAC_VERSION_FULL is generated by src/libmongoac/build.rs from VERSION_CURRENT.
    // It MUST NOT contain any null bytes and MUST NOT be invalid UTF-8.
    CS.get_or_init(|| CString::new(MONGOAC_VERSION_FULL).unwrap())
        .as_ptr()
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_prerelease() -> *const c_char {
    static CS: OnceLock<CString> = OnceLock::new();
    // SAFETY: MONGOAC_VERSION_PRERELEASE is generated by src/libmongoac/build.rs from VERSION_CURRENT.
    // It MUST NOT contain any null bytes and MUST NOT be invalid UTF-8.
    CS.get_or_init(|| CString::new(MONGOAC_VERSION_PRERELEASE).unwrap())
        .as_ptr()
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_check(
    required_major: i32,
    required_minor: i32,
    required_patch: i32,
) -> bool {
    let major = mongoac_version_major();
    let minor = mongoac_version_minor();
    let patch = mongoac_version_patch();

    major > required_major
        || (major == required_major && minor > required_minor)
        || (major == required_major && minor == required_minor && patch >= required_patch)
}
